// #7 verifier-plugin contract — build-trust REGRESSION gate.
//
// THE NON-NEGOTIABLE GATE: after build-trust.mjs is refactored to read its check-kind config from the
// shared resolver (verifiers/lib/policy.mjs) instead of hardcoded constants, regenerating trust.json
// from the CURRENT committed ledger must produce a result that is BYTE-IDENTICAL (EOL-normalized) to
// the committed registry/trust.json blob at HEAD.
//
// Why EOL-normalized: this repo has core.autocrlf=true, so the working-tree trust.json on disk has
// CRLF line endings while the HEAD blob (and the script's own JSON.stringify(...) + "\n" output) use
// LF. We compare the bytes the SCRIPT produces (LF) against the HEAD blob (LF), both normalized to LF,
// so the comparison is purely about CONTENT, never about the platform's line-ending policy.
//
// If this test fails, the refactor changed scoring — the v2-policy-driven path is no longer identical
// to the pre-#7 hardcoded path. That is a HARD regression and must be fixed before merge.

import { describe, it } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { buildTrust } from "../scripts/build-trust.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, "..", "..");

// Normalize CRLF -> LF so the comparison is content-only (autocrlf-proof).
const lf = (s) => s.replace(/\r\n/g, "\n");

// The committed trust.json AS GIT STORES IT (LF), independent of the working-tree's autocrlf state.
function headTrustJson() {
  return execFileSync("git", ["show", "HEAD:registry/trust.json"], {
    cwd: REPO_ROOT,
    encoding: "utf8",
  });
}

describe("#7 build-trust byte-identical regression gate (the non-negotiable gate)", () => {
  it("regenerating trust.json from the current ledger is byte-identical (EOL-normalized) to HEAD", () => {
    // Build into an ISOLATED temp registry dir so we never disturb the real working-tree trust.json.
    // Every other input (ledger, nodes, profiles, verifier.policy.json) is the REAL repo state, so this
    // exercises the production scoring path end-to-end against the live ledger.
    const tmpRegistry = fs.mkdtempSync(path.join(os.tmpdir(), "rm-regen-"));
    buildTrust({
      root: REPO_ROOT,
      registryDir: tmpRegistry,
      write: true,
    });
    const regenerated = fs.readFileSync(path.join(tmpRegistry, "trust.json"), "utf8");

    const head = headTrustJson();

    // The actual gate: content must match exactly once line endings are normalized.
    assert.equal(
      lf(regenerated),
      lf(head),
      "trust.json regenerated by the refactored (resolver-driven) build-trust must be byte-identical " +
        "(EOL-normalized) to the committed HEAD blob. A difference means the resolver path changed scoring."
    );
  });

  it("the in-memory build output serializes identically to HEAD (no hidden write-path divergence)", () => {
    // Belt-and-suspenders: prove the pure return value (write:false) serializes to the same bytes the
    // committed file holds, so the gate does not depend on the atomic-write path at all.
    const out = buildTrust({ root: REPO_ROOT, write: false });
    const serialized = JSON.stringify(out, null, 2) + "\n";
    assert.equal(
      lf(serialized),
      lf(headTrustJson()),
      "the buildTrust() return value must serialize byte-identically (EOL-normalized) to HEAD trust.json"
    );
  });
});
